# Trade list (supervised MM session).
[[markets]]
slug    = "will-gavin-newsom-win-the-2028-democratic-presidential-nomination-568"
profile = "newsom-mm"
enabled = false

[[markets]]
slug    = "will-alexandru-nazare-be-the-next-prime-minister-of-romania"
profile = "romania-pm"
enabled = false


[[markets]]
slug    = "will-luiz-incio-lula-da-silva-win-the-2026-brazilian-presidential-election"
profile = "fed-sept-mm"
enabled = true
base_size_usdc = 150

[[markets]]
slug    = "will-there-be-no-change-in-fed-interest-rates-after-the-september-2026-meeting-615"
profile = "fed-sept-mm"
enabled = true
base_size_usdc = 300
